Aws prov
rhpit/manageiq-cli pull request #97
Opened 2018-02-08 19:26 UTC by smatula

Add Amazon (AWS) provisioning request. Updated Provider.
New methods get_entity and get attribute. Allow the ability to obtain cloud_subnets

2018-02-08 20:08 UTC, ryankwilliams approved these changes
LGTM.

I left a couple comments for future adjustments. Not critical impacting this PR from being merged.

2018-02-08 20:08 UTC, ryankwilliams commented on example/aws_provision_example.py
> +while(not done):
Just wanted to note the parentheses are redundant. Can be removed in a future commit.

2018-02-08 20:08 UTC, ryankwilliams commented on miqcli/provider.py
> +        return output
We should assign the local variable `output` before the `try except` block. Not critical just cosmetic.

2018-02-08 20:08 UTC, rywillia commented on miqcli/constants.py
> +REQUIRED_AWSP_AUTO_PLACEMENT_KEYS = ["email", "image", "flavor", "vm_name"]
Should `AWSP` be `AWS`?

2018-02-08 20:08 UTC, rywillia commented on miqcli/constants.py
> +AWSP_PAYLOAD = {
Same as the comment above about the `AWSP`.

2018-02-08 21:43 UTC, vi-patel commented on miqcli/provider.py
> +            log.debug("Error getting element {0} for """
It would be good to print out the exact exception message in the debug message.

2018-02-08 21:45 UTC, vi-patel commented on miqcli/provider.py
> +        atts = self.get_entity(ent_id, attribute).__getattr__(attribute)
There could be an exception if the attribute doesn't exist for the specific entity, it would be good to catch this exception.

2018-02-08 21:48 UTC, vi-patel commented on miqcli/constants.py
> +SUPPORTED_PROVIDERS = ["OpenStack", "Amazon"]
Can we also change Amazon to AWS?

2018-02-08 21:50 UTC, vi-patel requested changes
Can we update w/the suggested changes?

2018-02-09 20:18 UTC, vi-patel approved these changes
looks good.

2018-02-09 20:20 UTC, merged